gridsingularity/gsy-e

src/d3a/d3a_core/simulation.py, src/d3a/setup/jira/d3asim_895_pr1.py, src/d3a/setup/jira/d3asim_895_pr2.py, src/d3a/setup/jira/d3asim_895_pr3.py
There seams to be a difference between randomisation behaviour if you run integration tests with be have or run the simulation in the command line.
We could not figure out how to fix that, so fixed the integrationtests (the consumption of the load).
=> D3ASIM-909: Fixed the bug in the integrationtests.

src/d3a/d3a_core/simulation.py
I did not remove the function implementation because I have the feeling that we might need this function in the future.
=> D3ASIM-1083: Removed check that all areas should have unique names.

src/d3a/models/area/__init__.py, tests/test_area.py
This is part 2 of the restriction to have duplicate area names inside the same parent area
[D3A web side](https://github.com/gridsingularity/d3a-web/pull/1122)
=> D3ASIM-2845 Prevent Duplicate area naming in the same Area

requirements/base.in, requirements/base.txt, requirements/pandapower.txt
This is needed to deserialize timezone aware timestamps send by the d3a-web.
=> added_pytz_to_requirements

.pre-commit-config.yaml
- Update `.pre-commit-config.yaml` to point to the latest version (3.4.0) of [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks)
- Replace `flake8` as recommended in the [release notes of pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v3.0.0)
D3A uses `pre-commit-hooks` along with the config file `.pre-commit-config.yaml` to set up git's pre-commit hooks.
Our `pre-commit-config.yaml` file is quite outdated, so we have warnings like the following:
```
[WARNING] normalizing pre-commit configuration to a top-level map.  support for top level list will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] Unexpected key(s) present on git://github.com/pre-commit/pre-commit-hooks: sha
```
Upgrading to …
=> Update pre-commit hooks generation and remove warnings

requirements/base.in, requirements/base.txt, requirements/blockchain.txt, requirements/dev.in, requirements/dev.txt, requirements/pandapower.in, requirements/pandapower.txt, requirements/tests.in, requirements/tests.txt, tox.ini
Some environments were relying on reciprocally incompatible dependencies.
For example, `ptpython` was definied in both `tests.in` and `dev.in`. In order to keep it internally compatible with the other packages of each environment, `pip-tool` will install a different version of its sub-dependency `pygments` in the two environments.
`fab sync` therefore tried to sync all the requirement files (`base.txt`, `dev.txt` and `tests.txt`) and failed.
In order to fix this problem (and a similar problem with `pandapower.txt`) we refactor the inheritance between requirements files. We make both `tests.in` and `pandapower.in` depend on `dev.txt`.
=> Fix dependencies between requirements environments

src/d3a/models/area/__init__.py
The simulation results that can be downloaded by the users contain a directory structure based on the names of the areas in the scenario. If these names contain invalid characters (like `/`) the export process will either fail or be compromised.
Our previous solution was to restrict the allowed characters in area names. However, this created incompatibilities with several simulations that had already been created by users in the past. We therefore decided to allow those characters again, but to sanitize them when generating the paths for the downloaded results (see https://github.com/gridsingularity/d3a-web/pull/1326).
=> D3ASIM-3450: remove validation of area names

src/d3a/models/strategy/load_hours.py
Reset price rates to be equal to the initial rate just once, before looping over each market.
=> Fix market cycle event for loads

src/d3a/models/strategy/home_meter.py
This PR corrects some `if` statements that were causing exceptions when no offers were present.
=> Fix case when offer is None in Home Meter tick event

codecov.yml, setup.py
I have recently adapted to a suggestion to remove the d3a-interface installation from setup.py as it is already covered in the requirements
However, there is a check here that skips the requirements starting with -e prefix, so the d3a-interface was being skipped and the deploys were failing
I have reverted the original setup in this PR
=>  Revert d3a-interface installation in setup.py

src/d3a/models/strategy/external_strategies/__init__.py, src/d3a/models/strategy/external_strategies/pv.py, src/d3a/models/strategy/external_strategies/storage.py
The `timeslot` parameter is breaking the current implementation for bids and offers:
- when the bid/offer arguments contains `{"timeslot": None}`
- when the `timeslot` parameter is passed to the `Offer` as an init parameter
This PR fixes these issues restoring the correct functionality of our integration tests (on the d3a-api-client side).
=> D3ASIM-3598: fix issues with timeslot parameter

.pre-commit-config.yaml, .pylintrc, requirements/dev.in, requirements/dev.txt
- Add Pylint as a pre-commit hook
- disable `missing-module-docstring` warnings
=> D3ASIM-3649: Add Pylint pre-commit hook

.pre-commit-config.yaml, requirements/dev.in, requirements/dev.txt, requirements/pandapower.txt, requirements/tests.txt
`pre-commit` installs its hooks (e.g. `pylint`) in a separate virtual environment. In this virtualenv we don’t have any of the libraries needed by our code (e.g. d3a-interface) so this version of pylint raises errors.
This PR allows using the local executable of Pylint (from the current virtual env) to avoid this kind of issues.
=> Use local Pylint executable in pre-commit hooks

src/d3a/models/myco_matcher/myco_internal_matcher.py
Resolves this exception that was raised on dev environment:
Traceback (most recent call last):
Nov 3, 2021 @ 11:50:24.822  File "/app/src/d3a/d3a_core/rq_job_handler.py", line 125, in launch_simulation_from_rq_job
Nov 3, 2021 @ 11:50:24.822    kwargs=kwargs)
Nov 3, 2021 @ 11:50:24.822  File "/app/src/d3a/d3a_core/simulation.py", line 622, in run_simulation
Nov 3, 2021 @ 11:50:24.822    simulation.run()
Nov 3, 2021 @ 11:50:24.822  File "/app/src/d3a/d3a_core/simulation.py", line 228, in run
Nov 3, 2021 @ 11:50:24.822    else self._execute_simulation(initial_slot, tick_resume)
Nov 3, 2021 @ 11:50:24.822  File "/app/src/d3a/d3a_core/simulation.py", line 379, in _execute_simulation
Nov 3, 2021 @ 11:50:24.822    self.area.tick_and_dispatch()
Nov 3, 2021 @ 11:50:24.822  File …
=> D3ASIM-3635: Removed market_count from the d3a-interface.

src/d3a/models/strategy/external_strategies/__init__.py, src/d3a/models/strategy/external_strategies/forecast_mixin.py, src/d3a/models/strategy/external_strategies/load.py, src/d3a/models/strategy/external_strategies/pv.py, src/d3a/models/strategy/external_strategies/storage.py, tox.ini
This PR deals with the following: 
- moving the forecast and measurement part of the external strategies from ExternalMixin to their own mixin, in order for the ExternalMixin to include only code that is always necessary for every mixin (need to extend this in order to abstract BidExternalMixin and OfferExternalMixin too)
- declaring the dependencies of the mixins as type hints, in order to have more clarity over which members does the mixed-in  class need to have in order for the mixin to work correctly. 
The initial approach to declare abstract methods for all the needed members did not work out unfortunately, because the Mixins need to precede the class that inherits them in the MRO order (in order to override methods that the mixed-in strategy class defines, e.g. event_tick). …
=> External strategy abc

integration_tests/steps/storage_test.py, src/d3a/d3a_core/user_profile_handler.py, src/d3a/models/market/balancing.py, src/d3a/models/market/one_sided.py, src/d3a/models/market/two_sided.py, tests/market/test_market.py
Solved the failing "Strategies follow yearly user profile saved in the DB" integration test, which could be reproduced only in local environments and not on CI nor production. The root cause of the bug was that the profile timeseries that are stored in the database were timezone-aware, therefore there are conversion methods that translate any timezone in the DB to UTC. However, the default Python timezone methods (`astimezone`) do not take into account DST, therefore in any environment with a local timezone with DST, the integration tests were failing. CI and production remained unaffected because they were running on UTC time anyways. 
Solution was to move from Python timezone methods to pendulum timezone methods, which solved the problem and translated the timezones taking into account …
=> Timezone integration tests

requirements/blockchain.in, requirements/blockchain.txt
Fix remnant of rebranding. The old d3a-blockchain repo is now called gsy-dex.
=> Rename old d3a-blockchain references to gsy-dex

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/models/area/__init__.py, src/gsy_e/models/area/event_dispatcher.py, src/gsy_e/models/area/markets.py, src/gsy_e/models/area/stats.py, src/gsy_e/models/market/__init__.py, src/gsy_e/models/market/one_sided.py, src/gsy_e/models/strategy/__init__.py, src/gsy_e/models/strategy/area_agents/one_sided_agent.py, src/gsy_e/models/strategy/external_strategies/__init__.py, src/gsy_e/models/strategy/external_strategies/storage.py, src/gsy_e/models/strategy/load_hours.py, src/gsy_e/models/strategy/settlement/strategy.py, src/gsy_e/models/strategy/smart_meter.py, tests/area/test_area.py, tests/area/test_event_dispatcher.py
This is the first PR that handles the renaming of "Area" into "Market". This name should be used in every part of the code that affects either researchers or UI users. Internally, the `Area` class can be preserved because it represents a different concept (since it represents both markets and assets).
=> D3ASIM-3553: Rename Area to Market

wiki/mkdocs.yml
The local version can work without `index.md` but the production one returns a 404 error. This is another attempt to make the redirection work both locally and in production.
=> Revert mkdocs redirection address

wiki/mkdocs.yml
Unfortunately, the previous attempts did not work for both production and local versions. We revert to the initial version, with the redirect pointing to the online website.
=> Redirect to the online version of the wiki

src/gsy_e/models/market/__init__.py, src/gsy_e/models/market/future.py, tests/market/test_future.py
Actions covered by the implementation of this design:
```python
self.bids = {..}  # This will create a FutureOrders object and create relevant mappings
self.bids.pop(bid_id)  # This will pop this item from the {id: bid} and {time_slot: [bids_list]}
del self.bids[bid_id]  # Same as above
self.bids[bid_id] = bid  # Add the bid to the two mappings
self.bids.update({....})  # Same as above
```
=>  Wrap the orders mappings in future market

tools/docker-compose.yml
Building the Kafka container fails with 
> Command [/usr/local/bin/dub path /etc/kafka/ writable] FAILED !
This issue was introduced by the recent `7.0.1` release. This PR pins our Kafka image version to `7.0.0`.
- https://github.com/confluentinc/kafka-images/issues/127
=> Pin Kafka to the last version without permission issues

src/gsy_e/models/market/future.py, tests/market/test_future.py
2 Bugs were fixed in context of this PR
1. When the `FUTURE_MARKETS_DURATION_HOURS` == 0, we shouldn't create any future market but in reality, we were.
2. We were prolonging the future time slots starting from the first future market, which is not correct, for instance: FUTURE_MARKETS_DURATION_HOURS = 1, current_time_slot = 00:00:00, future_time_slot = 00:15:00, we were assigning the most_future_slot to be equal to 1 hour from the 00:15:00 slot -> 01:15:00, whereas it should be 01:00:00
=> Fix create_future_markets to avoid creating any future market if the global future duration is 0

src/gsy_e/models/area/event_dispatcher.py, src/gsy_e/models/market/future.py, src/gsy_e/models/market/one_sided.py, src/gsy_e/models/market/two_sided.py, src/gsy_e/models/strategy/external_strategies/load.py, src/gsy_e/models/strategy/load_hours.py, src/gsy_e/models/strategy/market_agents/future_agent.py, src/gsy_e/models/strategy/predefined_load.py, tests/strategies/market_agents/test_future_agent.py, tests/strategies/test_strategy_load_hours.py, tox.ini
[LoadHoursStrategy]: The energy requirements of future time slots were not getting updated as they were supposed to be .this is why they were not placing bids in the future markets, this PR adds support for this functionality
=> GSYE-95: Update energy requirements for loadhours in future markets

src/gsy_e/models/area/__init__.py, src/gsy_e/models/myco_matcher/myco_external_matcher.py
Enable the external matching for orders in settlement markets. The `"settlement_markets"` content was already available to the external myco matcher, but it wasn't being used to send orders to the myco SDK.
=> GSYE-109: Send settlement market orders to external myco

src/gsy_e/models/state.py, src/gsy_e/models/strategy/external_strategies/storage.py, src/gsy_e/models/strategy/storage.py, src/gsy_e/setup/gsy_e_settings.json
The "loss per hour" mechanism was used to gradually reduce the energy stored by storage assets. Since this mechanism is generating issues and users have no control over it, we are deprecating it. 
We might think of re-introducing it in the future if a good use-case scenario for it will arise.
=> GSYE-108: Remove loss per hours mechanism in storage assets

src/gsy_e/constants.py, src/gsy_e/gsy_e_core/cli.py, src/gsy_e/gsy_e_core/redis_connections/redis_area_market_communicator.py, src/gsy_e/gsy_e_core/rq_job_handler.py, src/gsy_e/gsy_e_core/util.py, src/gsy_e/models/config.py, src/gsy_e/models/myco_matcher/myco_external_matcher.py, tests/market/test_myco_external_matcher.py
In order to make sure that only one consumer on the gsy-web side is handling each of the events and responses sent by the gsy-e, the communication was moved from redis pubsub to redis queue. This was done for both myco matcher and external devices and aggregators. For local simulation runs, the original pubsub way is kept. The constants.SEND_EVENTS_RESPONSES_TO_SDK_VIA_RQ is handling the switch between the two ways.
Also part of this PR: Centralised the queue names in the gsy-framework and reused them here.
=> Bug/gsye 150 Send external events and responses via redis queue

src/gsy_e/models/market/two_sided.py, src/gsy_e/models/strategy/market_agents/two_sided_engine.py, tests/strategies/test_strategy_storage.py, tests/test_market_agent.py, tests/test_two_sided_market.py
We used to add grid fees to the orders' prices when they get forwarded to another market.
Now that the orders have other `price` source of truth (the ones in the requirements), when we add fees to the order.price we also have to add fees to all `price` key in all `order.requirements` list (otherwise offer seller may end up getting less than it requested)
=> GSYE-178: Enable grid fees accounting for DoF requirements

src/gsy_e/models/strategy/external_strategies/pv.py, src/gsy_e/models/strategy/predefined_pv.py, src/gsy_e/models/strategy/pv.py, tests/strategies/test_strategy_pv.py, tests/strategies/test_strategy_pvpredefined.py
The PV's strategy was not updating the energy availability for the future market, this PR adds the setter method ` set_produced_energy_forecast_kWh_future_market` for the future markets.
There is also another added method ` set_produced_energy_forecast_kWh_in_state` that basically wraps both the setter calls for the spot market and the future markets
=>  Update PV energy availability in future markets

src/gsy_e/models/strategy/market_agents/one_sided_engine.py, tests/test_market_agent.py
When being forwarded to a higher market, offers did not pass attributes and requirements to the creation of the new offer. This PR fixes the issue.
=> GSYE-211: Forward offers' attributes and requirements

src/gsy_e/models/strategy/external_strategies/__init__.py
This error is currently spamming our logs, but it is often caused by an incorrect order sent by the user. Therefore, the message is just part of the regular flow and should probably not be logged as an exception, but rather as an INFO message.
- Change log level of the `OrderCanNotBePosted` exception handling to `INFO`.
=> Fix log levels when receiving incorrect orders

.gitignore
The iSort configuration file is used by editors to figure out how to sort import statements. The alternative to this PR would be to actually push the `isort.cfg` file directly, but I have the feeling that the other team members are not needing this.
- Ignore iSort configuration file, to allow developers to define it individually.
---
=> Ignore iSort configuration file

src/gsy_e/gsy_e_core/exchange_jobs.py, src/gsy_e/gsy_e_core/launcher.py, src/gsy_e/gsy_e_core/redis_connections/aggregator.py, src/gsy_e/gsy_e_core/redis_connections/area_market.py, src/gsy_e/gsy_e_core/redis_connections/simulation.py, tests/test_d3a_core/test_redis_area_market_communicator.py
As `StrictRedis` class is deprecated, we decided to use `Redis` instead.
- Renaming all `StrictRedis` occurrences to `Redis`.
=> WIP: GSYE-165: Renamed 'StrictRedis' to 'Redis' as it is deprecated.

src/gsy_e/gsy_e_core/export.py
- In order to match the file names listed in the [Result Download](https://gridsingularity.github.io/gsy-e/results-download/) doc, and as requested by [GSYE-188](https://gridsingularity.atlassian.net/browse/GSYE-188)
- Added a dictionary to map aggregated simulation result names (keys) to appropriate file names.
=> GSYE-188: Added a dictionary to map aggregated simulation result names to appropriate file names.

fabfile.py
As asked by [GSYE-53](https://gridsingularity.atlassian.net/browse/GSYE-53)
- calling `write_default_settings_file` task at the end of `fab sync` task.
=> GSYE-53: Update settings file with every fab sync run.

src/gsy_e/models/market/two_sided.py, tests/test_two_sided_market.py
The BidOfferMatch objects provided by the myco-sdk are directly used by the gsy-e to validate and confirm the trade. Thus, it is crucial to make sure that the provided BidOfferMatch is valid and matches the corresponding offer/bid of the market.
- Fix `_get_offer_from_seller_origin_id` to avoid unwanted match in the market
- Fix `_get_bid_from_buyer_origin_id` to avoid unwanted match in the market
- Override the offer/bid object of the recommended match provided by the myco-sdk with the corresponding offer/bid object from the market to avoid myco-sdk to manipulate the market
- Validate that `selected_energy` of a recommended match to be greater than 0
- Validate Validate a matching_requirement actually exists in the Bid/Offer object of the market
- Add unit tests for checking the match …
=> ENHANCEMENT/GSYE-183: Validate different attributes of the BidOfferMatch object 

src/gsy_e/gsy_e_core/rq_job_handler.py
The extra `pricing_scheme` keyword argument causes `launch_simulation_from_rq_job` to fail.
- Remove `pricing_scheme` from **kwargs passed to `run_simulation`
=> GSYE-323: Remove excessive keyword argument: `pricing_scheme`

src/gsy_e/models/area/markets.py
Since the Offer and Bid gets `creation_time` from the Market `now` attribute, it should be populated before the market cycle, and not only in `execute_actions_after_tick_event`.
Add `update_clock` in `activate_future_markets` to populate `now` attribute for future markets.
=> GSYE-276: Set the clock updater in the activate_future_markets

src/gsy_e/models/strategy/future/strategy.py, src/gsy_e/models/strategy/load_hours.py, src/gsy_e/models/strategy/pv.py, src/gsy_e/models/strategy/smart_meter.py, src/gsy_e/models/strategy/storage.py
The future market strategies's state isn't cleared for markets that become spots (they are no longer future markets).
Add a call to the delete_past_state method in the future strategies that clears both bid and offer rate updaters' states.
=> GSYE-334: Delete the spot market state from the future market strategy

src/gsy_e/models/strategy/future/strategy.py, src/gsy_e/models/strategy/update_frequency.py
The bug is raised when we instantiate the future updater as TemplateStrategyUpdaterInterface because it doesn't have all the attributes of the TemplateStrategyUpdaterBase
Another solution to this problem would be to add these missing attributes to the interface, if you favor it let me know. 
=> GSYE-334: Fix the delete_past_state_values of the future market strategies

src/gsy_e/gsy_e_core/rq_job_handler.py, tests/test_rq_job_utils.py
As `launch_simulation_from_rq_job` is the only entrypoint to running a simulation from the rq. It seems fair to have a test for this function ([GSYE-324](https://gridsingularity.atlassian.net/browse/GSYE-324)).
- Add `TestRQJobUtils` class
- Minor refactor to `launch_simulation_from_rq_job`
=> GSYE-324: Add unittest for launch_simulation_from_rq_job

tests/test_rq_job_utils.py
Python can't pickle a local object when using multiprocessing.Process, thus the fn function is moved to the scope of TestRQJobUtils.
- Move helper function `fn` to a non-local scope
=> Bug/GSYE-343: Move helper function `fn` to a non-local scope

src/gsy_e/gsy_e_core/exchange_jobs.py
In the dev logs I'm seeing a generic error:
```
Log message: TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
This kind of error log doesn't make it easy to debug the issue, as it doesn't contain a traceback to understand where in the code the error appeared.
- Change the log level of the simulation entrypoint to be `exception` (which shows the traceback).
=> Use exception logs to log simulation errors

wiki/docs/assets-installation.md
The markdown in the github wiki is broken. For example:
- Fix the markdown
=> Fix markdown in documentation

requirements/base.txt, requirements/blockchain.txt, requirements/dev.txt, requirements/pandapower.txt, requirements/tests.txt
- Fix dependency name for backports-entry-points-selectable
=> GSYE-364: Fix backports-entry-points-selectable==1.1.0 installation error

src/gsy_e/gsy_e_core/enums.py, src/gsy_e/gsy_e_core/market_counters.py, src/gsy_e/models/area/event_dispatcher.py, src/gsy_e/models/area/market_rotators.py, src/gsy_e/models/area/markets.py, src/gsy_e/models/market/forward.py, src/gsy_e/models/myco_matcher/myco_internal_matcher.py, tests/market/test_forward.py
An intraday market block is added that is a pre-configured FutureMarkets block
- Add INTRADAY market type, rotator and matcher
=> Feature/gsye 294 Add Intraday market

src/gsy_e/models/area/markets.py
Since the Offer and Bid gets `creation_time` from the Market now attribute, it should be populated before the market cycle, and not only in `execute_actions_after_tick_event`.
Add `update_clock` in `_activate_future_markets` to populate `now` attribute for future markets.
=> GSYE-276: Set the clock updater in the _activate_future_markets

src/gsy_e/gsy_e_core/launcher.py, src/gsy_e/gsy_e_core/util.py
Based on [GSYE-369](https://gridsingularity.atlassian.net/browse/GSYE-369) issue while running Simulation/CN get stuck in initializing state and does not run. It happens because of pod memory usage limit is reached.
Added function to check (based of specific files) whether to start the simulation.
=> GSYE-369: Added control in order to start simulation based on pod memory usage

src/gsy_e/models/area/__init__.py
1. Forward markets are missing the clock updates to track the creation time of the orders and trades.
2. We iterate through [_forward_match_algorithms](https://github.com/gridsingularity/gsy-e/blob/964d7a9e65c51acdaa281ed4e84a2c47ad50aebc/src/gsy_e/models/myco_matcher/myco_matcher_forward.py#L54) and trying to get the proper market from [area_uuid_markets_mapping](https://github.com/gridsingularity/gsy-e/blob/964d7a9e65c51acdaa281ed4e84a2c47ad50aebc/src/gsy_e/models/myco_matcher/myco_matcher_forward.py#L58), but the INTRADAY is missing.
1. Update the clock of the forward markets
2. Add intraday market to forward_markets_mapping
-
=> Fix forward market clock and mapping

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/models/myco_matcher/myco_matcher_forward.py
As requested by [GSYE-373](https://gridsingularity.atlassian.net/browse/GSYE-373), we wanted to add bids/offers/trades of forward markets to SimulationEndpointBuffer.
- Add `_read_forward_markets_stats_to_dict` method
- Skip non-existing area market_types while matching recommendations of forward markets
- Fix code style
=> feature/GSYE-373: Add bids/offers/trades of forward markets to SimulationEndpointBuffer

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py
AvailableMarketTypes objects are not json serializable.
- Use AvailableMarketTypes.value
=> GSYE-373-2: Use AvailableMarketTypes.value instead of AvailableMarketTypes

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py
We want to transfer only bids/offers/trades that have happened in the current simulation time of forward markets. 
- Add `_get_current_forward_orders_from_timeslot`
=> feature/GSYE-373-3: Filter bids/offers/trades of forward market based on current time_slot

src/gsy_e/gsy_e_core/enums.py, src/gsy_e/gsy_e_core/export.py, src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/gsy_e_core/sim_results/file_export_endpoints.py, src/gsy_e/models/area/__init__.py, src/gsy_e/models/area/event_dispatcher.py, src/gsy_e/models/area/markets.py, src/gsy_e/models/myco_matcher/myco_external_matcher.py, src/gsy_e/models/myco_matcher/myco_internal_matcher.py, src/gsy_e/models/myco_matcher/myco_matcher_forward.py, tests/area/test_area.py, tests/area/test_event_dispatcher.py, tests/market/test_myco_external_matcher.py
Move `AvailableMarketTypes`' definition to gsy-framework as this class is going to be used in other repos as well.
- Move `AvailableMarketTypes`' definition to gsy-framework
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-375
=> feature/GSYE-375: Move AvailableMarketTypes' definition to gsy-framework

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py
This PR is related to https://github.com/gridsingularity/gsy-framework/pull/388. For forward markets we need to only export open and unmatched bids/offers to the ResultsAggregator.
- Only export open and unmatched bids/offers of forward markets
=> GSYE-386: Only export open and unmatched bids/offers of forward markets

src/gsy_e/models/strategy/energy_parameters/load.py, src/gsy_e/models/strategy/energy_parameters/smart_meter.py, src/gsy_e/models/strategy/load_hours.py, src/gsy_e/models/strategy/scm/load.py, src/gsy_e/models/strategy/scm/smart_meter.py, src/gsy_e/models/strategy/smart_meter.py
The `decrement_energy_requirement()` method is currently called by the strategy directly on the `state` instance. This is not optimal: all interactions with energy parameters should be delegated to the `*EnergyParameters` classes (which will in turn call the state's methods).
**Update:** this PR also contains two bugfixes for SCM smart meters (when buying/selling energy).
- Implement `decrement_energy_requirement()` method on the energy parameter classes (for consumption devices)
- In the strategy classes, replace the calls made to `state.decrement_energy_requirement()` with `energy_params.decrement_energy_requirement()`
---
=> Refactor decrement energy to always delegate actions to energy params class

tests/test_endpoint_buffers.py
As requests by [GSYE-373](https://gridsingularity.atlassian.net/browse/GSYE-373) and asked by @fievelk.
- Add unit test for checking functionality of SimulationEndpointBuffer while generating forward market stats.
=> GSYE-373-3: Add unit tests for _read_forward_markets_stats_to_dict

src/gsy_e/gsy_e_core/simulation/simulation.py, src/gsy_e/gsy_e_core/simulation/time_manager.py
*NOTE: The duplicated key exception was never spotted again after Hannes' fix. This PR resolves only some other minor issues.*
- `slot_time_counter` increases irregularly because of accumulated miliseconds.
- Status of simulation is not set to "running" before the initial sleep of `calculate_total_initial_ticks_slots`.
```
slot_no start_of_slot
506 2022-10-07T16:52:00.022406+02:00
507 2022-10-07T16:53:35.357447+02:00
508 2022-10-07T16:55:35.457563+02:00
509 2022-10-07T16:57:35.557277+02:00
510 2022-10-07T16:59:35.657843+02:00
511 2022-10-07T17:01:35.741415+02:00
512 2022-10-07T17:03:35.840907+02:00
513 2022-10-07T17:05:35.942096+02:00
514 2022-10-07T17:07:36.042252+02:00
515 2022-10-07T17:09:36.140363+02:00
516 2022-10-07T17:11:36.223580+02:00
517 2022-10-07T17:13:36.297965+02:00
518 …
```
=> GSYE-388-2: Fix SCM time-related failures

src/gsy_e/gsy_e_core/user_profile_handler.py
If there is an empty profile in the DB, the code will fail with an IndexError that is not very understandable.
Add a custom exception that is raised if there is an empty profile in the DB that is about to be read. 
=> GSYE-417: Add raise of exception when profile in DB is empty.

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, tests/test_endpoint_buffers.py
As requested by GSYE-446, we want to calculate and store asset volume time series for forward markets.
capacity_kW is needed to generate the scaled ssp profile of the volume time series.
- Add `capacity_kW` to exported kafka results for forward markets.
=> GSYE-446: Export capacity_kW in area_dict for forward markets

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py
As requested by [GSYE-444](https://gridsingularity.atlassian.net/browse/GSYE-444), we want to want to remove all traces of high-resolution graphs for the offer/bid/trade and the energy trade profile
=> GSYE-444: Remove last_energy_trades_high_resolution

tox.ini
Main change involves sharing the same environment across all tox targets, thus allowing to separate the setup process to a separate target and creating dedicated targets for running the unit and integration tests that do not invoke the setup process (therefore do not try to reinstall the packages). 
The approach worked well in the terminal, however does not work well with the Pycharm tox runners. In order to configure it in Pycharm a configuration for unittests and setup needs to be created (in order to not have to invoke these via terminal but directly in your IDE):  
It generally works, what does not work though is the ability to run individual tests through tox, because the Pycharm tox runner does not support this. 
-
=> Share tox env

src/gsy_e/models/config.py, tests/test_rq_job_utils.py
=> Fix handling of case when aggregator_device_mapping is an empty dict

src/gsy_e/gsy_e_core/area_serializer.py, src/gsy_e/models/leaves.py, src/gsy_e/models/strategy/profile.py, src/gsy_e/models/strategy/scm/external/load.py, src/gsy_e/models/strategy/scm/external/pv.py, src/gsy_e/models/strategy/scm/load.py, src/gsy_e/setup/scm/external.py
We need the SCMLoadHoursStrategy in  the ExternalSCMLoadStrategy in order to initiate a profile with 0 values for the forecast SCM strategies.
I also propose to rename the ExternalSCMLoadStrategy into ForecastSCMLoadStrategy. What do you think @spyrostz ?
-
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-434
=> GSYE-434: Fix ExternalSCMLoadStrategy

wiki/docs/connect-ctn.md, wiki/mkdocs.yml
=> update_wiki: Fix some titles

src/gsy_e/gsy_e_core/util.py, src/gsy_e/models/strategy/forward/order_updater.py, src/gsy_e/models/strategy/heat_pump.py, src/gsy_e/models/strategy/order_updater.py, tests/strategies/test_heat_pump.py
=> GSYE-767: Enable passing profiles to OrderUpdaterParameters

src/gsy_e/gsy_e_core/export.py, src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/gsy_e_core/simulation/results_manager.py, src/gsy_e/gsy_e_core/simulation/simulation.py, tests/test_endpoint_buffers.py
=> GSYE-568: Add create_hierarchy_stats to SimulationEndpointBuffer

src/gsy_e/gsy_e_core/sim_results/file_export_endpoints.py, src/gsy_e/models/strategy/__init__.py, src/gsy_e/models/strategy/state/__init__.py, src/gsy_e/models/strategy/state/storage_state.py, src/gsy_e/models/strategy/storage.py, src/gsy_e/setup/strategy_tests/storage_with_losses.py
-
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-645
=> GSYE-645: Add loss calculation to storage state

src/gsy_e/gsy_e_core/export.py, src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, tests/test_endpoint_buffers.py
=> GSYE-568: Change hierarchy self consumption into percentage values

setup.py
=> GSYE-830: Omit SCM requirement in case the SCM repo is not defined.
