gridsingularity/gsy-e

src/d3a/d3a_core/simulation.py, src/d3a/models/config.py, src/d3a/models/const.py
Added a sleep which synchronises the simulation runtime with the real time.
=> D3ASIM-1129: Added real-time support for running the simulation.

src/d3a/d3a_core/area_serializer.py, src/d3a/models/strategy/storage.py
This is not the fix of the bug (its done in d3a-web).
This is just an add on, that enables us to use area_serializer.area_to_string() to use for debugging.
=> D3ASIM-1170: Improved AreaSerialiser.

requirements/base.in, requirements/base.txt, src/d3a/d3a_core/simulation.py, src/d3a/models/area/event_dispatcher.py, src/d3a/models/market/__init__.py, src/d3a/models/strategy/area_agents/balancing_agent.py, src/d3a/models/strategy/area_agents/inter_area_agent.py, src/d3a/models/strategy/area_agents/one_sided_agent.py, src/d3a/models/strategy/area_agents/two_sided_pay_as_bid_agent.py, src/d3a/models/strategy/load_hours.py
... in order to be independent from the OS.
=> D3ASIM-1172: Changed random number generation to numpy.random.

src/d3a/d3a_core/d3a_jobs.py
I also took the opportunity to set the logging level to critical.
=> D3ASIM-1367: Readded market_maker_rate to d3a_jobs.py.

src/d3a/setup/jira/d3asim_2420.py, src/d3a/setup/jira/d3asim_2421.py, src/d3a/setup/jira/d3asim_2422.py, src/d3a/setup/two_sided_market/default_2a_high_res_graph.py
-Set-up files for tickets 2420-2422
=> Set-up files for Offer_bid_trade graph testing and tickets

src/d3a/d3a_core/cli.py
D3ASIM2634- Slowdown Factor In Cli to float
=> Slowdown Factor in Cli to flot

src/d3a/models/strategy/market_maker_strategy.py
=> Removed type check in area_reconfigure_event , as it is now validated from the d3aweb side

integration_tests/steps/integration_tests.py, integration_tests/steps/jira_issues_tests.py, src/d3a/d3a_core/sim_results/endpoint_buffer.py
To be merged before https://github.com/gridsingularity/d3a/pull/1033
=> Enhancing cumulative grid trades.

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/pandapower.txt, requirements/tests.txt
Sync urllib version with that of d3a-api-client/ d3a-interface
=> Urllib version sync

README.rst
Add coverage badge for Codecov in README file.
=> D3ASIM-3484: add coverage badge in README

src/d3a/models/strategy/commercial_producer.py, src/d3a/models/strategy/finite_power_plant.py, src/d3a/models/strategy/load_hours.py, src/d3a/models/strategy/market_maker_strategy.py, src/d3a/models/strategy/pv.py, src/d3a/models/strategy/storage.py, tests/test_home_meter.py, tests/test_market.py
Implement validators as classes for improved maintainability (potentially allow to avoid redundancy).
=> Use validator classes to replace functions

src/d3a/models/strategy/commercial_producer.py, src/d3a/models/strategy/finite_power_plant.py, src/d3a/models/strategy/home_meter.py, src/d3a/models/strategy/load_hours.py, src/d3a/models/strategy/market_maker_strategy.py, src/d3a/models/strategy/pv.py, src/d3a/models/strategy/storage.py, tests/test_home_meter.py
Linked to gridsingularity/d3a-interface#230
=> Refactor device validations imports

.github/workflows/d3a_ci.yaml, .github/workflows/d3a_ci_cd_development.yaml, .github/workflows/d3a_ci_cd_staging.yaml
github actions slack notifications
=> DEV-86: github actions slack notifications

.github/workflows/d3a_ci.yaml
=> DEV-94: Remove CI slack notifications

src/d3a/d3a_core/export.py, src/d3a/d3a_core/sim_results/file_export_endpoints.py
I also homogenized the time columns. With Chris we agreed that both, the slot time and the actual time of posting the bid or offer or the actual time of the trade is useful information. 
Connected PR: https://github.com/gridsingularity/d3a-interface/pull/266
=> Bug/d3 asim 3614 Fixed export of csv files

src/gsy_e/models/strategy/load_hours.py
The pylint warnings are fixed commit by commit
=> loadhours.py deal with pylint styling warnings

src/gsy_e/models/state.py, tests/test_state/test_storage_state.py
The first commit is the actual fix whereas the second one is a pylint warnings fixes
I did enable future markets in the integration tests and all features passed
=> GSYE-85: Fix the storage state bug when the future markets are enabled

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/gsy_e_core/util.py, src/gsy_e/models/strategy/infinite_bus.py, tests/strategies/test_strategy_infinite_bus.py, tox.ini
Earlier a constant value was being used to calculate feed-in tariff as reference for SavingsKPI, this PR targets it to be linked with energy buy rate of `InfiniteBus`
=> GSYE-73: Use energy buy rate of InfiniteBus as feed-in tariff.

src/gsy_e/models/state.py, tests/test_state/test_storage_state.py
This PR contains unit-tests for StorageState class methods.
=> TESTS-109: Create unit tests for the storage state.

src/gsy_e/setup/strategy_tests/external_devices_send_forecasts.py
=> TESTS-114: As gsy-e-sdk I like to add an integration test that will check sending forecasts is reflected in the results

setup.cfg, setup.py
=> Bump version: 1.2.0 → 1.3.0

README.rst, tox.ini
Modularization of the testenvs in tox file was improved for gsy-web repository. The changes on this repo will match up with that done on gsy-web.
Improve the modularization of the tox configuration environments.
=> TESTS-143: I want to reduce tox files redundancy on tox file testenvs.

src/gsy_e/models/market/grid_fees/constant_grid_fees.py, src/gsy_e/models/market/two_sided.py, tests/test_two_sided_market.py
=> GSYE-205: Enable residual requirements when DoF is activated

wiki/docs/asset-api-commands.md, wiki/docs/registration-matching-api-backend.md
- asset-api-commands.md
- registration-matching-api-backend.md
-
=> Correcting typos and minor changes in the following sections:

wiki/docs/grid-operator-api-template-script.md
=> grid-operator-api-template-script

src/gsy_e/models/leaves.py, src/gsy_e/models/state.py, src/gsy_e/models/strategy/external_strategies/__init__.py, src/gsy_e/models/strategy/external_strategies/load.py, src/gsy_e/models/strategy/external_strategies/pv.py, src/gsy_e/models/strategy/external_strategies/smart_meter.py, src/gsy_e/models/strategy/external_strategies/storage.py, src/gsy_e/setup/strategy_tests/external_smart_meter.py, tests/strategies/external/test_smart_meter.py
As requested by [GSYE-15](https://gridsingularity.atlassian.net/browse/GSYE-15): Open the Smart Meter asset to external connection
- Implement `SmartMeterExternalStrategy`
- Write tests for `SmartMeterExternalStrategy`
- Small refactors to other external strategies
- [GBIT](https://github.com/gridsingularity/gsy-backend-integration-tests/pull/60)
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-15
=> Feature/GSYE-15: Open the Smart Meter asset to external connection

src/gsy_e/gsy_e_core/rq_job_handler.py
=> Reverted log level of the root logger to error.

wiki/docs/get-simulation-data.md
=> Fixed URL in APIs documentation

wiki/docs/get-simulation-data.md
=> Updated Grid Data API documentation

src/gsy_e/gsy_e_core/area_serializer.py, src/gsy_e/gsy_e_core/sim_results/file_export_endpoints.py, src/gsy_e/gsy_e_core/sim_results/plotly_graph.py, src/gsy_e/models/area/__init__.py, src/gsy_e/models/area/scm_manager.py, src/gsy_e/models/leaves.py, src/gsy_e/models/strategy/scm/load.py, src/gsy_e/setup/gsy_e_settings.json, tests/test_area_serializer.py, tests/test_live_events.py
=> GSYE-370: Omit null children from the Area constructor.

.github/workflows/gsy-e_ci.yaml
Run CI tests on all branches
-
=> DEV-250: remove branches

src/gsy_e/models/strategy/energy_parameters/load.py, src/gsy_e/models/strategy/energy_parameters/pv.py, src/gsy_e/models/strategy/energy_parameters/smart_meter.py, src/gsy_e/models/strategy/external_strategies/load.py, src/gsy_e/models/strategy/external_strategies/smart_meter.py, src/gsy_e/models/strategy/load_hours.py, src/gsy_e/models/strategy/predefined_load.py, src/gsy_e/models/strategy/predefined_pv.py, src/gsy_e/models/strategy/pv.py, src/gsy_e/models/strategy/scm/load.py, src/gsy_e/models/strategy/scm/pv.py, src/gsy_e/models/strategy/scm/smart_meter.py, src/gsy_e/models/strategy/smart_meter.py, tests/strategies/test_strategy_load_hours.py, tests/strategies/test_strategy_pv.py, tests/strategies/test_strategy_smart_meter.py
=> GSYE-333: Moved EnergyParameters classes to their own Python package

src/gsy_e/setup/two_sided_market/load_fitlimits_match.py
Ad integration test
-
**INTEGRATION_TESTS_BRANCH**=GSYE-340
=> GSYE-340: Fit to limits box should be checked by default

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, src/gsy_e/gsy_e_core/simulation.py, tests/test_endpoint_buffers.py, tests/test_simulation.py
Add more tests for the `SimulationEndpointBuffer` and `CoefficientEndpointBuffer` classes.
---
=> GSYE-390: Add tests for simulation endpoint buffers

wiki/mkdocs.yml
=> Updated documentation

src/gsy_e/models/area/coefficient_area.py
=> GSYE-425: Fix bug due to merge of refactoring branch

src/gsy_e/gsy_e_core/simulation/simulation.py, src/gsy_e/gsy_e_core/simulation/status_manager.py
=> Fix handling 'paused' in cli mode for SCM simulations

src/gsy_e/gsy_e_core/rq_job_handler.py
=> Made config type an optional parameter in the gsy-e job handler.

src/gsy_e/models/strategy/future/strategy.py, tests/strategies/future/test_future_strategy.py
This is not fixing the issue, but implements a fix 
-
=> GSYE-424: Improve tracking posted order in future storage strategy

src/gsy_e/gsy_e_core/rq_job_handler.py
=> Improve logging when launching simulation from gsy-web

src/gsy_e/models/strategy/__init__.py, src/gsy_e/models/strategy/external_strategies/storage.py, tests/strategies/external/test_load.py, tests/strategies/external/test_pv.py, tests/strategies/external/test_smart_meter.py, tests/strategies/external/test_storage.py, tests/strategies/test_strategy_base.py
=> feature/GSYE-349: Add future market tests for ExternalStorageStrategy

src/gsy_e/gsy_e_core/area_serializer.py, src/gsy_e/models/base.py, src/gsy_e/models/leaves.py, src/gsy_e/models/state.py, src/gsy_e/models/strategy/energy_parameters/heat_pump.py, src/gsy_e/models/strategy/heat_pump.py, src/gsy_e/models/strategy/new_base_strategy.py, src/gsy_e/models/strategy/scm/__init__.py, tests/strategies/test_heat_pump.py
-
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-427
=> GSYE-427: Add HeatPumpStrategy and tests

tests/test_endpoint_buffers.py
=> GSYE-447: Test for normal simulation of endpoint buffer.

src/gsy_e/models/market/one_sided.py, src/gsy_e/models/market/two_sided.py, tests/test_endpoint_buffers.py
=> Fix trade bid info

src/gsy_e/gsy_e_core/sim_results/file_export_endpoints.py, src/gsy_e/models/state.py, src/gsy_e/models/strategy/energy_parameters/heat_pump.py, src/gsy_e/models/strategy/heat_pump.py, src/gsy_e/models/strategy/profile.py, src/gsy_e/setup/strategy_tests/heat_pump.py, tests/strategies/energy_parameters/heat_pump.py, tests/strategies/test_heat_pump.py
-
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-426
=> Feature/gsye 426 Add EnergyParamters for the HeatPump

src/gsy_e/models/area/scm_manager.py, tests/area/test_coefficient_area.py
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-477
=> GSYE-477: Make use of KPICalculationHelper

wiki/docs/connection-energy-assets.md, wiki/docs/registration-asset-api-backend.md, wiki/docs/registration-asset-api-user-interface.md, wiki/docs/registration-grid-operator-api-backend.md, wiki/docs/send-data-rest-api.md
=> Remove references to d3a

tests/area/test_coefficient_area.py
=> fix_savings_percentage

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py, tests/test_endpoint_buffers.py
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-452
**GSY_FRAMEWORK_BRANCH**=bug/GSYE-452
=> GSYE-452: Integrate validation with AVRO schemas

src/gsy_e/gsy_e_core/redis_connections/simulation.py, src/gsy_e/gsy_e_core/simulation/simulation.py
-
**INTEGRATION_TESTS_BRANCH**=bug/GSYE-513
=> Bug/gsye 513 Fix callback channel for RedisSimulationCommunication._calculate_area_map_callback

src/gsy_e/gsy_e_core/bc_connection/simulation.py, src/gsy_e/models/area/area.py, src/gsy_e/models/market/one_sided_bc.py, src/gsy_e/models/market/two_sided_bc.py, src/gsy_e/models/strategy/__init__.py
=> Fix execution

src/gsy_e/models/strategy/heat_pump.py
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-428
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-428
=> GSYE-428: Populate order_updater_params for HeatPump strategy

src/gsy_e/models/leaves.py, src/gsy_e/models/strategy/scm/external/load.py, src/gsy_e/setup/scm/external.py
-
**INTEGRATION_TESTS_BRANCH**=feature/GSYE-434
=> GSYE-562: Fix issue with external SCM strategies

src/gsy_e/models/strategy/scm/external/forecast_mixin.py, src/gsy_e/models/strategy/scm/external/load.py, src/gsy_e/models/strategy/scm/external/pv.py
=> fix_forecast_scm_strategies

src/gsy_e/models/leaves.py, src/gsy_e/models/strategy/scm/external/pv.py
=> GSYE-581: Allow unused parameter capacity_kW in ForecastSCMPVStrategy

src/gsy_e/models/strategy/state/storage_state.py
=> GSYE-558: Handle case when storage was set up to have 0 capacity

src/gsy_e/models/strategy/energy_parameters/heat_pump.py, src/gsy_e/models/strategy/heat_pump.py
=> Enable HeatPump Strategy to also take comsumption profiles

src/gsy_e/gsy_e_core/simulation/simulation.py
=> GSYE-588: Send 'stopped' status if the simulation was stopped

wiki/mkdocs.yml
=> Changed title of blockchain wiki section to GSy DEX Overview.

src/gsy_e/gsy_e_core/rq_job_handler.py, src/gsy_e/gsy_e_core/user_profile_handler.py, src/gsy_e/models/area/scm_manager.py
=> Fix scm past slots

src/gsy_e/setup/scm/external.py
=> Fix gsy e sdk tests

src/gsy_e/constants.py
=> Modified the SCM CN days of delay to 3 days.

src/gsy_e/models/strategy/energy_parameters/heat_pump.py, src/gsy_e/models/strategy/state/heat_pump_state.py
=> Corrected heatpump consumption profile.

src/gsy_e/models/strategy/energy_parameters/heat_pump.py, src/gsy_e/models/strategy/state/heat_pump_state.py
=> Dev to prod 2023 09 04 2

src/gsy_e/constants.py, src/gsy_e/models/area/scm_manager.py, src/gsy_e/models/strategy/energy_parameters/heat_pump.py, tests/area/test_coefficient_area.py
=> Dev to prod 2023 09 14

src/gsy_e/models/strategy/energy_parameters/heat_pump.py
-
**INTEGRATION_TESTS_BRANCH**=bug/GSYE-631
=> GSYE-631: Fix _calc_energy_to_buy_minimum in HP energy parameters

src/gsy_e/gsy_e_core/sim_results/endpoint_buffer.py
-
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-514
=> GSYE-514: Validate simulation state before sending to gsy-web

wiki/mkdocs.yml
=> update_wiki: Update one more title

src/gsy_e/models/strategy/heat_pump.py, tests/strategies/test_heat_pump.py
=> GSYE-651: Add use_market_maker_rate to HeatPumpOrderUpdaterParameters

wiki/docs/licensing.md
=> RES-148: Removed duplicated licensing sentence.

src/gsy_e/models/market/one_sided.py, src/gsy_e/models/market/two_sided.py, src/gsy_e/models/strategy/order_updater.py, tests/strategies/forward/test_strategies.py, tests/strategies/test_heat_pump.py, tests/strategies/test_order_updater.py
=> GSYE-650: Fix OrderUpdater order rate progression

wiki/docs/connect-ctn.md
=> Last fixes on the documentation of the canary network connection.

src/gsy_e/setup/area_events/load_event.py, src/gsy_e/setup/two_sided_market/load_fitlimits_match.py
-
**INTEGRATION_TESTS_BRANCH**=bug/GSYE-711
=> GSYE-711: Fix provision of hrs_of_day in setups

src/gsy_e/gsy_e_core/rq_job_handler.py, tests/test_gsy_core/test_rq_job_handler.py
=> Fix scm_cn_hours_of_delay

requirements/base.in, requirements/base.txt, setup.py
=> add psycopg2 and psycopg2-binary to base requirements

.github/workflows/gsy-e_ci.yaml, fabfile.py, requirements/base.txt, requirements/dev.txt, requirements/tests.txt, setup.py, src/gsy_e/setup/gsy_e_settings.json, tox.ini
=> Bump requirements

wiki/docs/heat-pump.md
=> Updated HP wiki

src/gsy_e/gsy_e_core/export.py
-
**GSY_FRAMEWORK_BRANCH**=feature/GSYE-736
=> GSYE-736: Add imported_exported_energy to json exports

wiki/docs/market-types.md, wiki/docs/trading-agents-and-strategies.md
=> RESEARCH-112: Styling fixes.

src/gsy_e/gsy_e_core/sim_results/plotly_graph.py
=> GSYE-772: increase font size, width and height of plots

src/gsy_e/gsy_e_core/util.py, src/gsy_e/models/area/coefficient_area.py, src/gsy_e/models/area/scm_dataclasses.py, src/gsy_e/models/area/scm_manager.py
=> Dev to prod 2024 10 17

src/gsy_e/models/area/scm_dataclasses.py
=> Removed assertion for savings_absolute

wiki/docs/data-requirements.md
=> Small fixes on the charge / discharge power of the storage.

src/gsy_e/models/market/two_sided.py
=> GSYE-851: Improve logging of bid creation and deletion

wiki/docs/carbon-footprint-savings.md
=> RESEARCH-383: Corrected table structure to render the URLs correctly.

wiki/docs/aggregate-market-summary.md, wiki/docs/carbon-footprint-savings.md, wiki/docs/duplicating-simulations.md, wiki/docs/price.md, wiki/docs/results-download.md, wiki/docs/trade-profile.md, wiki/docs/trades.md
=> RESEARCH-383: Corrected comments on Carbon Footprint wiki page.

wiki/docs/carbon-footprint-savings.md
=> RESEARCH-383: Modified carbon footprint table header.

src/gsy_e/models/strategy/energy_parameters/heatpump/heat_pump.py
=> HSB_LL: Fix small bug
